### PR TITLE
Code we won't use

### PR DESCRIPTION
**Pull request by demipixel**
\>.\>

### CODE REVIEW

**Comment by rom1504** [comment]
The section thing is interesting.

I think we should inspire ourselves from the vanilla help thing.

**Comment by demipixel** [comment]
Lol vanilla doesn't have the section thing, but I figured most plugins would need it.

**Comment by rom1504** [comment]
Hmm what are sections ? I meant the page thing.

**Comment by demipixel** [comment]
Section means it is a command with multiple sub-commands. For example, /time has "set", "add", and "query" (although vanilla doesn't do it this way, it's just an example).

If a plugin, such as world edit, wanted to make a section /we, they would do:

```js
serv.newSection('we', {
  help: 'World Edit Commands'
}
```

Then it's easy to add commands. The section is dedicated by how the command is created. `time` means the section is the default section (i.e. ''), `we time` would mean it was section we> time, `we test time` would mean we > test > time, etc

```js
serv.newSection('we shape', ...);
serv.addCommand('we shape sphere', ...);
serv.addCommand('we shape cube', ...);
serv.addCommand('we fill', ...);
```

As you can see, any section can contain both sub-sections or its own commands. Finally, help commands are automatically created for every single section in the format:

/[section-list] <command> [page-n (optional)]

or

/[section-list] [page-n (optional)]

**Comment by rom1504** [comment]
can probably be used in #42

**Comment by demipixel** [comment]
?????????? Can I delete this and my plugins branch? (old branch from like months ago)

**Comment by rom1504** [comment]
improving the commands is not over and I bet there are still interesting stuff in the plugins branch ;)

**Comment by rom1504** [comment]
Hmm, let's close this. We can always work on it, and the code won't disapear, but it'll be in an other PR anyway.
Let's track work on this in https://github.com/mhsjlw/flying-squid/issues/92

**Pull request closed without merging**
