### PR TITLE
Mini worldgen change

### PR DESCRIPTION
**Pull request by demipixel**
Should be good. Added grass, added bedrock/dirt line, matched the waterline (I believe)

### CODE REVIEW

**Comment by rom1504** [comment]
can you rebase on master ? (git rebase master then follow the instructions)

**Comment by rom1504** [comment]
Too often it's completely under water

**Comment by rom1504** [comment]
@JWo1F can you look at this ? I'm pretty sure the Math.random doesn't make sense relatively to the diamond square algo.

**Comment by demipixel** [comment]
Math.random stuff is more for population-type things. Minecraft doesn't make worlds exactly the same, it's just the terrain looks similar (it's never exactly the same) and the grass/trees/ores are all in different positions (caves are the same I believe).

If the grass isn't in the same place every time or the bedrock doesn't come up from the bottom exactly the same, nobody is going to notice, and I believe that is how Minecraft does it.

**Comment by rom1504** [comment]
It's not so much about whether minecraft does this that way or not, it's about if the diamond square algorithm does it that way. And it doesn't seem like that.

Why do you need dirtheight ? doesn't DiamondSquare give that already ? ( @JWo1F ?)

**Comment by demipixel** [comment]
No, it was grass and then only dirt underneath. I made it grass, then a few blocks of dirt, then stone (like normal minecraft).

**Pull request merged**
