### PR TITLE
LOL LMAO ROFL XD XD XP XP XP

### PR DESCRIPTION
**Pull request by demipixel**
XP

### CODE REVIEW

**Comment by rom1504** [comment]
Can you add doc for these functions ? (so we don't have to add lot and lot of docs later)

**Comment by rom1504** [comment]
Oh well, I kind of failed my merge, but all the commits are in master now.

**Comment by mhsjlw** [comment]
@rom1504, we should really start thinking about a way to store all of this stuff like a function that stores key-values? It would be good to start saving info on players.

**Comment by rom1504** [comment]
@mhsjlw yes, but we probably want to start by using the vanilla storage format

**Comment by mhsjlw** [comment]
Do we really need to do that? I think it would make more sense maybe just making a wrapper around an sqlite3 server that starts when flying-squid does, then just make methods for storing data in the database. Then, if we wanted to we could make a converter that converts the database to world format and so on so forth. Also, we could add abilities to add different databases other than sqlite3 like PostgreSQL and MongoDB and MySQL

**Comment by rom1504** [comment]
@mhsjlw I think we should be able to use different backend, but the default should be vanilla.

But if you want to start working on a non-vanilla backend, feel free to ;)

**Comment by rom1504** [comment]
also see https://github.com/PrismarineJS/prismarine-world/issues/11

**Pull request closed without merging**
