### PR TITLE
Come with me, and you'll be...

### PR DESCRIPTION
**Pull request by demipixel**
... in a worllllld of [pure plugins!](https://youtu.be/r2pt2-F2j2g?t=27s)

To test:

1. Clone this branch or whatever
2. Go to plugins folder, create redditbuilds
3. Add an index.js with [this](http://hastebin.com/ofokacuwer.js) and `npm init` the folder
4. Go to /config, duplicate default_settings.json into settings.json
5. Add a plugin `"redditbuilds": {}` inside "plugins"
6. ???
6. Profit. Probably. Hopefully.

### CODE REVIEW

**Comment by rom1504** [comment]
I don't understand why you need to create a folder inside plugins/

**Comment by demipixel** [comment]
Because a plugin is a module. That way, plugins can install any other modules they want. Lastly, it makes it extremely easy to npm publish with no issues.

**Comment by rom1504** [comment]
Any file that does module.exports = {} is a module. But okay fine.

**Comment by demipixel** [comment]
@rom1504 I think it would work without the folder, however if I were teaching someone about this, I would teach them to create a folder since it's best practice and since they'll hopefully be publishing it.

**Comment by rom1504** [comment]
Yeah yeah sure, I agree.

**Comment by 109C** [comment]
@demipixel Also, it makes plugins/ cleaner if people want to split their plugin into multiple files.

**Comment by rom1504** [comment]
Alright, it works fine, nice.

**Pull request merged**
