### PR TITLE
The Start of World Generation

### PR DESCRIPTION
**Pull request by demipixel**
Works.

'nuf said.

### CODE REVIEW

**Comment by rom1504** [comment]
discussion in #45

**Comment by demipixel** [comment]
So what changes need to be made to this at this point?

**Comment by rom1504** [comment]
Alright so, I think the WorldGen thing is too specific and having a simpler API like just generateChunk is simpler and better.
But your superflat generation works, so could you add it there https://github.com/mhsjlw/flying-squid/tree/master/src/lib/worldGenerations ? (you don't need WorldGen at all for superflat)

**Comment by rom1504** [comment]
Hmm well I guess an options object should be passed to the generation though. (so we can configure the 138 of https://github.com/mhsjlw/flying-squid/blob/master/src/lib/worldGenerations/diamond_square.js#L108 for example)

**Comment by rom1504** [comment]
Alright so I added options. It should be possible to add that superflat.

**Comment by rom1504** [comment]
Okay, done in c4974f8e3388dd8e63843d110d9dd5889717bfc4 , thanks !

**Pull request closed without merging**
