### PR TITLE
ModPE support

### PR DESCRIPTION
**Pull request by Creeplays**

### CODE REVIEW

**Comment by Creeplays** [comment]
Now working

**Comment by Creeplays** [comment]
Added more api functions. WorldEdit (and some other scripts) can be now imported.

**Comment by Creeplays** [comment]
TODO: auto removing GUI from mods

**Comment by Creeplays** [comment]
DO NOT MERGE FOR NOW

**Comment by rom1504** [comment]
Why did you close this ?

**Comment by Creeplays** [comment]
I am pushed modpe support to other branch. See other pull request

**Pull request closed without merging**
