### PR TITLE
ModPe scripts as plugin

### PR DESCRIPTION
**Pull request by Creeplays**
Currently loads only one script, and his script is WorldEdit.
Full ModPe api in future.

### CODE REVIEW

**Comment by Creeplays** [comment]
image

**Comment by rom1504** [comment]
Oh wow it's huge.

Anyway this totally fit the current external plugin architecture  ( https://github.com/mhsjlw/flying-squid/blob/master/doc/contribute.md#creating-external-plugins )

**Comment by Creeplays** [comment]
Core modpe support module should be a core plugin i think.

**Comment by rom1504** [comment]
What do you mean by "core modpe" ?
But clearly the content of this PR should be an external plugin, it's way too big to maintain in flying-squid.

But thanks for doing it, it's nice !

We just need to figure out how best to make it available, I think an external plugin fits.

**Comment by Creeplays** [comment]
Will be in this repo: https://github.com/Creeplays/squid-modpe

**Comment by rom1504** [comment]
Ah this is really nice https://github.com/Connor4898/ModPE-Docs/wiki/Documentation

I didn't know about modpe,.

**Comment by Creeplays** [comment]
ModPE have a lot bigger list of functions and hooks, this wiki updated along time ago.

**Pull request closed without merging**
